[package]
name = "rust_1brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
memchr = "2.7.2"
memmap2 = "0.9.4"
